#!/bin/bash
# Script: rebuild-manifest.sh
# Description: Rebuild Teams App manifest for any environment
# Usage: ./rebuild-manifest.sh [playground|local|dev|prod]
# Default: prod
# Nomenclature: ADR-017 (rebuild-manifest.sh)

set -euo pipefail

# Determine environment (default: prod)
ENV="${1:-prod}"

# Validate environment
VALID_ENVS="playground local dev prod"
if [[ ! "$VALID_ENVS" =~ (^|[[:space:]])"$ENV"($|[[:space:]]) ]]; then
    echo "❌ Error: Invalid environment '$ENV'"
    echo "   Valid options: $VALID_ENVS"
    echo "   Usage: bash scripts/rebuild-manifest.sh [playground|local|dev|prod]"
    exit 1
fi

ENV_FILE="env/.env.${ENV}"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "❌ Error: Environment file $ENV_FILE not found"
    exit 1
fi

# Load environment variables
set -a
source "$ENV_FILE"
set +a

echo "🔧 Rebuilding manifest for: ${ENV}"
echo "   Version: ${TEAMS_APP_VERSION}"
echo "   RC Version: ${TEAMS_APP_RC_VERSION:-none}"
echo "   Suffix: '${APP_NAME_SUFFIX:-}'"
echo "   App ID: ${TEAMS_APP_ID:-N/A}"
echo "   Bot ID: ${BOT_ID:-N/A}"

# Create build directory
cd appPackage
mkdir -p build

# FULL_VERSION should be provided by .env file (generated by YAML provision step)
# Fallback: construct it if not present (for manual script execution)
if [ -z "${FULL_VERSION:-}" ]; then
    echo "⚠️  FULL_VERSION not found in .env, constructing from TEAMS_APP_VERSION..."
    if [ -n "${TEAMS_APP_RC_VERSION:-}" ]; then
        FULL_VERSION="${TEAMS_APP_VERSION} (${TEAMS_APP_RC_VERSION})"
    else
        FULL_VERSION="${TEAMS_APP_VERSION}"
    fi
fi

# Substitute ${{VAR}} with actual values using sed
# IMPORTANT: Version JSON doit être SIMPLE (4.0.7), description peut avoir RC (4.0.7 (rc2))
OUTPUT_FILE="build/manifest.${ENV}.json"

# Remove existing file to avoid permission issues
rm -f "$OUTPUT_FILE"

sed -e "s/\${{TEAMS_APP_VERSION}}/${TEAMS_APP_VERSION}/g" \
    -e "s/\${{FULL_VERSION}}/${FULL_VERSION}/g" \
    -e "s/\${{APP_NAME_SUFFIX}}/${APP_NAME_SUFFIX:-}/g" \
    -e "s/\${{TEAMS_APP_ID}}/${TEAMS_APP_ID:-placeholder}/g" \
    -e "s/\${{BOT_ID}}/${BOT_ID:-placeholder}/g" \
    manifest.json > "$OUTPUT_FILE"

echo "✅ Manifest rebuilt successfully"
echo "📄 Output: appPackage/$OUTPUT_FILE"
